---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  # network:
  # - ["forwarded_port", {guest: 8080, host: 8080}]

provisioner:
  name: chef_zero
  data_bags_path: 'test/integration/default/data_bags'
  roles_path: 'test/integration/default/roles'
  environment_path: 'test/integration/default/environments'

platforms:
  - name: centos-6.7
    run_list:
      - recipe[yum::default]

  # - name: ubuntu-12.04
  #   run_list:
  #     - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[tcserver::default]
      - role[war_hotel]
    attributes:
